name: build
on:
  push:
    branches: [master]
    paths-ignore: 
      - "**.md"
  pull_request:
    branches: [master]
    paths-ignore: 
      - "**.md"
      - ".github/workflows/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.2", "8.3"]

    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php }}

      - name: phpunit
        uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
          php_version:  ${{ matrix.php }}
          test_suffix: .php
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: Scarlett
    
